= B2

B2 makes it easy to build C++ projects, everywhere.

image:https://img.shields.io/badge/license-BSL%201.0-blue.svg["Boost Software License 1.0", link="LICENSE.txt"]
image:https://img.shields.io/github/languages/code-size/bfgroup/b2.svg["GitHub code size in bytes", link="https://github.com/bfgroup/b2"]

== License

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE.txt or copy at https://www.bfgroup.xyz/b2/LICENSE.txt)

== Testing

Continuously tested on:

* FreeBSD Clang 11, 12, 13, 14, 15, 16, 17
* FreeBSD GCC 9, 10, 11, 12, 13
* Linux Clang 3.6, 3.7, 3.8, 3.9, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17
* Linux GCC 4.8, 4.9, 5, 6, 7, 8, 9, 10, 11, 12, 13
* macOS Xcode 11.7, 12.4, 12.5.1, 13.4.1, 14.0.1, 14.1, 14.2, 14.3.1, 15.0.1
* Windows MinGW 8.1.0
* Windows 2015, 2017, 2019, 2022
* Windows MSYS2 MinGW64/32 Clang-16, MinGW64/32 GCC-13
* Cygwin 3.1.7 x64
* Ubuntu 22.04 GCC 11 (armhf, arm64, ppc64el)
* Ubuntu 20.04 GCC 9 (armhf, arm64, ppc64el)
* Debian 11 GCC 10 (armhf)

image:https://img.shields.io/azure-devops/build/bfgroup/3a4e7a7e-c1b4-4e2f-9199-f52918ea06c6/3/main.svg?label=main&logo=azuredevops["Linux/Windows/macOS: main", link="https://dev.azure.com/bfgroup/B2"]
image:https://img.shields.io/appveyor/build/bfgroup/b2?logo=appveyor["Windows", link="https://ci.appveyor.com/project/bfgroup/b2"]
image:https://img.shields.io/cirrus/github/bfgroup/b2?logo=cirrusci&label=release["FreeBSD: release", link="https://cirrus-ci.com/github/bfgroup/b2/release"]
image:https://img.shields.io/cirrus/github/bfgroup/b2?logo=cirrusci&label=main["FreeBSD: main", link="https://cirrus-ci.com/github/bfgroup/b2/main"]
image:https://img.shields.io/github/actions/workflow/status/bfgroup/b2/qemu_multiarch_linux.yml?logo=github["Ubuntu 22.04 GCC 11 (armhf, arm64, ppc64el)", link="https://github.com/bfgroup/b2/actions/workflows/qemu_multiarch_linux.yml"]
image:https://img.shields.io/github/actions/workflow/status/bfgroup/b2/core_tests.yml?logo=github["Windows MSYS2 MinGW64/32 Clang-16, MinGW64/32 GCC-13", link="https://github.com/bfgroup/b2/actions/workflows/core_tests.yml"]

NOTE: A {CPP}11 capable compiler is needed to build the `b2` engine. But using
the `b2` engine and build system does not require C++11.

== More

See the link:https://www.bfgroup.xyz/b2/[website] for more information.

See the link:CONTRIBUTING.adoc[guidelines for contributing] if you would like
to get involved in the development.
